name: learn-github-actions
on: [push]
jobs:
#  check-bats-version:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "this is pen"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: download
        run: |
          wget "https://script.google.com/macros/s/AKfycbwIv-WsvT_1EvcyIaVBa5jxAWPjF-6DjAe-tkSUS5oDNcOmNkzFKcUaVlhuxLejuOPo/exec?callback=_roadInfoCallback" -O ./roadinfo.js
      - name: gitconfig
        run: |
          git config --global user.email "kei.misawa@gmail.com"
          git config --global user.name "330k"
      - name: commit
        run: |
          git add .
          git commit -m 'Add JS' -a
          git pull
          git push origin main


